AWSTemplateFormatVersion: 2010-09-09

Resources:
  ### AWS CloudTrail
  Trail:
    Type: AWS::CloudTrail::Trail
    Properties:
      S3BucketName: "{{ organization.name }}-prd-security-log-bucket"
      IsLogging: true
      EnableLogFileValidation: true
      IncludeGlobalServiceEvents: true
      IsMultiRegionTrail: true

  ### AWS Config
  ConfigRecorderRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - config.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSConfigRole

  ConfigRecorder:
    Type: AWS::Config::ConfigurationRecorder
    Properties:
      RoleARN: !GetAtt ConfigRecorderRole.Arn
      RecordingGroup:
        AllSupported: true
        IncludeGlobalResourceTypes: true

  ConfigDeliveryChannel:
    Type: AWS::Config::DeliveryChannel
    Properties:
      Name: ConfigDeliveryChannel
      ConfigSnapshotDeliveryProperties:
        DeliveryFrequency: Twelve_Hours
      S3BucketName: "{{ organization.name }}-prd-security-log-bucket"

